CARGA, TRANSFORMACION Y LIMPIEZA DE DATOS

In [4]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns',None)

In [5]:
#Cargo el xlsx y creo un DataFrame.

df_customers = pd.read_excel('../Datos_Raw/customers.xlsx')
df_customers.head()

,customer_id,name,email,phone,signup_date,country,gender,age,income_bracket,address,city,state
0,3145,Paul Black,paul.black@example.com,311-809-1717,2018-11-27,UK,Unknown,32.0,medium,6604 Oak Ave,Sydney,ON
1,3859,Laura Adams,laura.adams@example.com,(861) 007 5325,NaN,France,Male,46.0,medium,1703 Cedar Ave,Paris,ENG
2,1569,Laura Wright,laura.wright@example.com,(518) 481 3267,2016/05/26,Australia,Female,36.0,Medium,1848 Birch Rd,Houston,CA
3,1795,Jane Clark,jane.clark@example.com,(750) 690 4925,09/05/2020,Germany,M,28.0,High,5751 Elm St,sydney,NY
4,1893,Alice Black,alice.black@example.com,(548) 954 7876,13-04-2021,Germany,female,52.0,High,4735 Cedar Ave,Toronto,TX

In [6]:
# Convierto el nombre de las columnas de ingles a español. Creo un diccionario
column_map_es = {
    'customer_id': 'id_cliente',
    'name': 'nombre',
    'email': 'correo',
    'phone': 'telefono',
    'signup_date': 'fecha_registro',
    'country': 'pais',
    'gender': 'genero',
    'age': 'edad',
    'income_bracket': 'nivel_ingresos',
    'address': 'direccion',
    'city': 'ciudad',
    'state': 'provincia'
}

df_customers = df_customers.rename(columns=column_map_es)
df_customers.head()

,id_cliente,nombre,correo,telefono,fecha_registro,pais,genero,edad,nivel_ingresos,direccion,ciudad,provincia
0,3145,Paul Black,paul.black@example.com,311-809-1717,2018-11-27,UK,Unknown,32.0,medium,6604 Oak Ave,Sydney,ON
1,3859,Laura Adams,laura.adams@example.com,(861) 007 5325,NaN,France,Male,46.0,medium,1703 Cedar Ave,Paris,ENG
2,1569,Laura Wright,laura.wright@example.com,(518) 481 3267,2016/05/26,Australia,Female,36.0,Medium,1848 Birch Rd,Houston,CA
3,1795,Jane Clark,jane.clark@example.com,(750) 690 4925,09/05/2020,Germany,M,28.0,High,5751 Elm St,sydney,NY
4,1893,Alice Black,alice.black@example.com,(548) 954 7876,13-04-2021,Germany,female,52.0,High,4735 Cedar Ave,Toronto,TX

In [7]:
# Convierto los nombres de columnas del DataFrame en letras capitales
df_customers.columns = [col.capitalize() for col in df_customers.columns]
df_customers.head()

,Id_cliente,Nombre,Correo,Telefono,Fecha_registro,Pais,Genero,Edad,Nivel_ingresos,Direccion,Ciudad,Provincia
0,3145,Paul Black,paul.black@example.com,311-809-1717,2018-11-27,UK,Unknown,32.0,medium,6604 Oak Ave,Sydney,ON
1,3859,Laura Adams,laura.adams@example.com,(861) 007 5325,NaN,France,Male,46.0,medium,1703 Cedar Ave,Paris,ENG
2,1569,Laura Wright,laura.wright@example.com,(518) 481 3267,2016/05/26,Australia,Female,36.0,Medium,1848 Birch Rd,Houston,CA
3,1795,Jane Clark,jane.clark@example.com,(750) 690 4925,09/05/2020,Germany,M,28.0,High,5751 Elm St,sydney,NY
4,1893,Alice Black,alice.black@example.com,(548) 954 7876,13-04-2021,Germany,female,52.0,High,4735 Cedar Ave,Toronto,TX

In [127]:
#Cargo el csv y creo un DataFrame.
df_sales = pd.read_csv('../Datos_RAW/sales.csv')
df_sales.head()

,sale_id,customer_id,sale_date,amount,product,quantity,discount,channel,region,status,shipping_zone,shipping_method,quantity_num,package_weight,amount_num,order_value_band,shipping_cost,id_canal,Id_producto
0,S00001,1119.0,2015-04-13,252.44,widget i,4.0,20%,Retail,North,Pending,Zone 1,Local,4.0,6.0,252.44,Medium,11.7,Tienda3,PROD-009
1,S00002,4149.0,2018-10-25,223.16,Widget F,8.0,15%,Mobile,East,Completed,Zone 3,Express,8.0,12.0,223.16,Medium,25.2,Tienda2,PROD-006
2,S00003,543.0,2017-07-22,985.37,Widget H,4.0,0.25,InStore,West,Pending,Zone 4,Pick-up,4.0,6.0,985.37,High,5.5,Tienda4,PROD-008
3,S00004,4131.0,2015-08-18,41.78,Widget J,7.0,0.05,InStore,West,Shipped,Zone 4,Pick-up,7.0,10.5,41.78,Low,15.5,Tienda4,PROD-010
4,S00005,474.0,2016-07-20,$100.00,Widget B,10.0,0.15,Online,East,Cancelled,Zone 3,Standard,10.0,15.0,100.00,Medium,18.9,Tienda1,PROD-002

In [9]:
# Convierto el nombre de las columnas de ingles a español
column_map_es = {
    'sale_id': 'id_venta',
    'customer_id': 'id_cliente',
    'sale_date': 'fecha_venta',
    'amount': 'importe',
    'product': 'producto',
    'quantity': 'cantidad',
    'discount': 'descuento',
    'channel': 'canal',
    'region': 'region',
    'status': 'estado',
    'shipping_zone': 'zona_envio',
    'shipping_method': 'metodo_envio',
    'quantity_num': 'cantidad_num',
    'package_weight': 'peso_paquete',
    'amount_num': 'importe_num',
    'order_value_band': 'rango_valor_pedido',
    'shipping_cost': 'coste_envio'
}


df_sales = df_sales.rename(columns=column_map_es)
df_sales.head()

,id_venta,id_cliente,fecha_venta,importe,producto,cantidad,descuento,canal,region,estado,zona_envio,metodo_envio,cantidad_num,peso_paquete,importe_num,rango_valor_pedido,coste_envio,id_canal,Id_producto
0,S00001,1119.0,2015-04-13,252.44,widget i,4.0,20%,Retail,North,Pending,Zone 1,Local,4.0,6.0,252.44,Medium,11.7,Tienda3,PROD-009
1,S00002,4149.0,2018-10-25,223.16,Widget F,8.0,15%,Mobile,East,Completed,Zone 3,Express,8.0,12.0,223.16,Medium,25.2,Tienda2,PROD-006
2,S00003,543.0,2017-07-22,985.37,Widget H,4.0,0.25,InStore,West,Pending,Zone 4,Pick-up,4.0,6.0,985.37,High,5.5,Tienda4,PROD-008
3,S00004,4131.0,2015-08-18,41.78,Widget J,7.0,0.05,InStore,West,Shipped,Zone 4,Pick-up,7.0,10.5,41.78,Low,15.5,Tienda4,PROD-010
4,S00005,474.0,2016-07-20,$100.00,Widget B,10.0,0.15,Online,East,Cancelled,Zone 3,Standard,10.0,15.0,100.00,Medium,18.9,Tienda1,PROD-002

In [10]:
# Convierto los nombres de columnas del DataFrame en letras capitales
df_sales.columns = [col.capitalize() for col in df_sales.columns]
df_sales.head()

,Id_venta,Id_cliente,Fecha_venta,Importe,Producto,Cantidad,Descuento,Canal,Region,Estado,Zona_envio,Metodo_envio,Cantidad_num,Peso_paquete,Importe_num,Rango_valor_pedido,Coste_envio,Id_canal,Id_producto
0,S00001,1119.0,2015-04-13,252.44,widget i,4.0,20%,Retail,North,Pending,Zone 1,Local,4.0,6.0,252.44,Medium,11.7,Tienda3,PROD-009
1,S00002,4149.0,2018-10-25,223.16,Widget F,8.0,15%,Mobile,East,Completed,Zone 3,Express,8.0,12.0,223.16,Medium,25.2,Tienda2,PROD-006
2,S00003,543.0,2017-07-22,985.37,Widget H,4.0,0.25,InStore,West,Pending,Zone 4,Pick-up,4.0,6.0,985.37,High,5.5,Tienda4,PROD-008
3,S00004,4131.0,2015-08-18,41.78,Widget J,7.0,0.05,InStore,West,Shipped,Zone 4,Pick-up,7.0,10.5,41.78,Low,15.5,Tienda4,PROD-010
4,S00005,474.0,2016-07-20,$100.00,Widget B,10.0,0.15,Online,East,Cancelled,Zone 3,Standard,10.0,15.0,100.00,Medium,18.9,Tienda1,PROD-002

In [11]:
# Convierto los valores de la columna Id_cliente a tipo entero.
df_sales['Id_cliente'] = pd.to_numeric(
	df_sales['Id_cliente'],
	errors='coerce'
).astype('Int64')

In [12]:
# 1. Convertir a texto
df_sales['Id_venta'] = df_sales['Id_venta'].astype(str)

# 2. Limpiar espacios
df_sales['Id_venta'] = df_sales['Id_venta'].str.strip()

# 3. Extraer solo el código correcto si hay comas
df_sales['Id_venta'] = df_sales['Id_venta'].str.split(',').str[0]

In [13]:
df_sales

,Id_venta,Id_cliente,Fecha_venta,Importe,Producto,Cantidad,Descuento,Canal,Region,Estado,Zona_envio,Metodo_envio,Cantidad_num,Peso_paquete,Importe_num,Rango_valor_pedido,Coste_envio,Id_canal,Id_producto
0,S00001,1119,2015-04-13,252.44,widget i,4.0,20%,Retail,North,Pending,Zone 1,Local,4.0,6.0,252.44,Medium,11.7,Tienda3,PROD-009
1,S00002,4149,2018-10-25,223.16,Widget F,8.0,15%,Mobile,East,Completed,Zone 3,Express,8.0,12.0,223.16,Medium,25.2,Tienda2,PROD-006
2,S00003,543,2017-07-22,985.37,Widget H,4.0,0.25,InStore,West,Pending,Zone 4,Pick-up,4.0,6.0,985.37,High,5.5,Tienda4,PROD-008
3,S00004,4131,2015-08-18,41.78,Widget J,7.0,0.05,InStore,West,Shipped,Zone 4,Pick-up,7.0,10.5,41.78,Low,15.5,Tienda4,PROD-010
4,S00005,474,2016-07-20,$100.00,Widget B,10.0,0.15,Online,East,Cancelled,Zone 3,Standard,10.0,15.0,100.00,Medium,18.9,Tienda1,PROD-002
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60095,S59170,4301,2018-01-07,39.08,Widget H,5.0,0.1,online,East,Shipped,Zone 3,Standard,5.0,7.5,39.08,Low,13.5,Tienda1,PROD-008
60096,S46252,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60097,S25974,1630,2019-05-15,72.11,Widget D,7.0,0.25,InStore,South,Cancelled,Zone 2,Pick-up,7.0,10.5,72.11,Low,14.5,Tienda4,PROD-004
60098,S25520,3161,2022-01-03,893.5,widget b,8.0,30%,Mobile,East,Completed,Zone 3,Express,8.0,12.0,893.50,High,14.0,Tienda2,PROD-002
60099,S21800,3579,2022-10-27,49.51,Widget F,5.0,0.15,Retail,West,Pending,Zone 4,Local,5.0,7.5,49.51,Low,17.5,Tienda3,PROD-006

In [14]:
# Reviso si hay valores duplicados en todas las columnas del DataFrame
df_sales.apply(lambda col: col.duplicated().sum())

Id_venta                100
Id_cliente            55099
Fecha_venta           57177
Importe               16612
Producto              60059
Cantidad              60089
Descuento             60085
Canal                 60091
Region                60091
Estado                60095
Zona_envio            60094
Metodo_envio          60095
Cantidad_num          60089
Peso_paquete          60089
Importe_num           18779
Rango_valor_pedido    60095
Coste_envio           59956
Id_canal              60095
Id_producto           60089
dtype: int64

In [15]:
# Reviso las filas y columnas de Id_venta duplicadas
df_sales[df_sales.duplicated(subset=['Id_venta'], keep=False)].sort_values(by='Id_venta')

,Id_venta,Id_cliente,Fecha_venta,Importe,Producto,Cantidad,Descuento,Canal,Region,Estado,Zona_envio,Metodo_envio,Cantidad_num,Peso_paquete,Importe_num,Rango_valor_pedido,Coste_envio,Id_canal,Id_producto
303,S00304,3952,2018-05-26,172.5,Widget B,9.0,30%,Online,West,Cancelled,Zone 4,Standard,9.0,13.5,172.50,Medium,19.35,Tienda1,PROD-002
60035,S00304,2468,2018-05-26,172.5,Widget B,9.0,30%,Online,West,Cancelled,Zone 4,Standard,9.0,13.5,172.50,Medium,19.35,Tienda1,PROD-002
60005,S00807,636,2020-05-14,435.78,widget i,3.0,20%,InStore,South,Cancelled,Zone 2,Pick-up,3.0,4.5,435.78,Medium,7.65,Tienda4,PROD-009
806,S00807,1705,2020-05-14,435.78,widget i,3.0,20%,InStore,South,Cancelled,Zone 2,Pick-up,3.0,4.5,435.78,Medium,7.65,Tienda4,PROD-009
60083,S01164,1126,2016-08-09,123.4,Widget D,4.0,0.3,online,North,Pending,Zone 1,Standard,4.0,6.0,123.40,Medium,9.90,Tienda1,PROD-004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60038,S58614,2510,2017-05-17,882.05,Widget E,10.0,25%,Retail,West,Cancelled,Zone 4,Local,10.0,15.0,882.05,High,12.50,Tienda3,PROD-005
59169,S59170,4199,2018-01-07,39.08,Widget H,5.0,0.1,online,East,Shipped,Zone 3,Standard,5.0,7.5,39.08,Low,13.50,Tienda1,PROD-008
60095,S59170,4301,2018-01-07,39.08,Widget H,5.0,0.1,online,East,Shipped,Zone 3,Standard,5.0,7.5,39.08,Low,13.50,Tienda1,PROD-008
60059,S59217,2390,2017-07-05,490.19,Widget H,9.0,0.15,Retail,South,Pending,Zone 2,Local,9.0,13.5,490.19,Medium,20.25,Tienda3,PROD-008
59216,S59217,2384,2017-07-05,490.19,Widget H,9.0,0.15,Retail,South,Pending,Zone 2,Local,9.0,13.5,490.19,Medium,20.25,Tienda3,PROD-008

In [16]:
# Ordeno id_venta y id_cliente de forma ascendente para unificar los registros duplicados y conservar el id_cliente menor por id_venta
df_sales_sorted = df_sales.sort_values(['Id_venta', 'Id_cliente'])
df_sales_sorted.head()

,Id_venta,Id_cliente,Fecha_venta,Importe,Producto,Cantidad,Descuento,Canal,Region,Estado,Zona_envio,Metodo_envio,Cantidad_num,Peso_paquete,Importe_num,Rango_valor_pedido,Coste_envio,Id_canal,Id_producto
0,S00001,1119,2015-04-13,252.44,widget i,4.0,20%,Retail,North,Pending,Zone 1,Local,4.0,6.0,252.44,Medium,11.7,Tienda3,PROD-009
1,S00002,4149,2018-10-25,223.16,Widget F,8.0,15%,Mobile,East,Completed,Zone 3,Express,8.0,12.0,223.16,Medium,25.2,Tienda2,PROD-006
2,S00003,543,2017-07-22,985.37,Widget H,4.0,0.25,InStore,West,Pending,Zone 4,Pick-up,4.0,6.0,985.37,High,5.5,Tienda4,PROD-008
3,S00004,4131,2015-08-18,41.78,Widget J,7.0,0.05,InStore,West,Shipped,Zone 4,Pick-up,7.0,10.5,41.78,Low,15.5,Tienda4,PROD-010
4,S00005,474,2016-07-20,$100.00,Widget B,10.0,0.15,Online,East,Cancelled,Zone 3,Standard,10.0,15.0,100.00,Medium,18.9,Tienda1,PROD-002

In [17]:
# Conservar solo la fila con Id_cliente menor por Id_venta
df_sales_clean = df_sales_sorted.drop_duplicates(subset=['Id_venta'], keep='first')

In [18]:
# Reviso si hay valores NA de la columna Id_cliente
df_sales['Id_cliente'].isna()
df_sales

,Id_venta,Id_cliente,Fecha_venta,Importe,Producto,Cantidad,Descuento,Canal,Region,Estado,Zona_envio,Metodo_envio,Cantidad_num,Peso_paquete,Importe_num,Rango_valor_pedido,Coste_envio,Id_canal,Id_producto
0,S00001,1119,2015-04-13,252.44,widget i,4.0,20%,Retail,North,Pending,Zone 1,Local,4.0,6.0,252.44,Medium,11.7,Tienda3,PROD-009
1,S00002,4149,2018-10-25,223.16,Widget F,8.0,15%,Mobile,East,Completed,Zone 3,Express,8.0,12.0,223.16,Medium,25.2,Tienda2,PROD-006
2,S00003,543,2017-07-22,985.37,Widget H,4.0,0.25,InStore,West,Pending,Zone 4,Pick-up,4.0,6.0,985.37,High,5.5,Tienda4,PROD-008
3,S00004,4131,2015-08-18,41.78,Widget J,7.0,0.05,InStore,West,Shipped,Zone 4,Pick-up,7.0,10.5,41.78,Low,15.5,Tienda4,PROD-010
4,S00005,474,2016-07-20,$100.00,Widget B,10.0,0.15,Online,East,Cancelled,Zone 3,Standard,10.0,15.0,100.00,Medium,18.9,Tienda1,PROD-002
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60095,S59170,4301,2018-01-07,39.08,Widget H,5.0,0.1,online,East,Shipped,Zone 3,Standard,5.0,7.5,39.08,Low,13.5,Tienda1,PROD-008
60096,S46252,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60097,S25974,1630,2019-05-15,72.11,Widget D,7.0,0.25,InStore,South,Cancelled,Zone 2,Pick-up,7.0,10.5,72.11,Low,14.5,Tienda4,PROD-004
60098,S25520,3161,2022-01-03,893.5,widget b,8.0,30%,Mobile,East,Completed,Zone 3,Express,8.0,12.0,893.50,High,14.0,Tienda2,PROD-002
60099,S21800,3579,2022-10-27,49.51,Widget F,5.0,0.15,Retail,West,Pending,Zone 4,Local,5.0,7.5,49.51,Low,17.5,Tienda3,PROD-006

In [19]:
# Reviso si hay valores NA en Id_cliente
df_sales[df_sales['Id_cliente'].isna()]

,Id_venta,Id_cliente,Fecha_venta,Importe,Producto,Cantidad,Descuento,Canal,Region,Estado,Zona_envio,Metodo_envio,Cantidad_num,Peso_paquete,Importe_num,Rango_valor_pedido,Coste_envio,Id_canal,Id_producto
24,S00025,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,S00026,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,S00028,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,S00042,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
72,S00073,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60077,S27791,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60079,S31833,<NA>,2022-10-28,779.41,Widget A,7.0,NaN,Retail,West,Cancelled,Zone 4,Local,7.0,10.5,779.41,High,10.25,Tienda3,PROD-001
60086,S20257,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60087,S22115,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60096,S46252,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:

# Convierto los valores de id_cliente a tipo numerico
df_sales['Id_cliente'] = pd.to_numeric(df_sales['Id_cliente'], errors='coerce')

In [21]:
# Elimino filas con valores NA
df_sales = df_sales[df_sales['Id_cliente'].notna()]
df_sales

,Id_venta,Id_cliente,Fecha_venta,Importe,Producto,Cantidad,Descuento,Canal,Region,Estado,Zona_envio,Metodo_envio,Cantidad_num,Peso_paquete,Importe_num,Rango_valor_pedido,Coste_envio,Id_canal,Id_producto
0,S00001,1119,2015-04-13,252.44,widget i,4.0,20%,Retail,North,Pending,Zone 1,Local,4.0,6.0,252.44,Medium,11.7,Tienda3,PROD-009
1,S00002,4149,2018-10-25,223.16,Widget F,8.0,15%,Mobile,East,Completed,Zone 3,Express,8.0,12.0,223.16,Medium,25.2,Tienda2,PROD-006
2,S00003,543,2017-07-22,985.37,Widget H,4.0,0.25,InStore,West,Pending,Zone 4,Pick-up,4.0,6.0,985.37,High,5.5,Tienda4,PROD-008
3,S00004,4131,2015-08-18,41.78,Widget J,7.0,0.05,InStore,West,Shipped,Zone 4,Pick-up,7.0,10.5,41.78,Low,15.5,Tienda4,PROD-010
4,S00005,474,2016-07-20,$100.00,Widget B,10.0,0.15,Online,East,Cancelled,Zone 3,Standard,10.0,15.0,100.00,Medium,18.9,Tienda1,PROD-002
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60094,S05081,3259,2017-06-24,144.94,Widget H,6.0,0.15,mobile,east,Shipped,Zone 3,Express,6.0,9.0,144.94,Medium,22.5,Tienda2,PROD-008
60095,S59170,4301,2018-01-07,39.08,Widget H,5.0,0.1,online,East,Shipped,Zone 3,Standard,5.0,7.5,39.08,Low,13.5,Tienda1,PROD-008
60097,S25974,1630,2019-05-15,72.11,Widget D,7.0,0.25,InStore,South,Cancelled,Zone 2,Pick-up,7.0,10.5,72.11,Low,14.5,Tienda4,PROD-004
60098,S25520,3161,2022-01-03,893.5,widget b,8.0,30%,Mobile,East,Completed,Zone 3,Express,8.0,12.0,893.50,High,14.0,Tienda2,PROD-002
60099,S21800,3579,2022-10-27,49.51,Widget F,5.0,0.15,Retail,West,Pending,Zone 4,Local,5.0,7.5,49.51,Low,17.5,Tienda3,PROD-006

In [22]:
# Reviso si existen valores NA, Nan, None en distintos datatypes y lo convierto en NA reales
df_sales['Id_cliente'] = df_sales['Id_cliente'].replace(['nan', 'None', 'NA', '<NA>'], pd.NA)
df_sales['Id_cliente'] = pd.to_numeric(df_sales['Id_cliente'], errors='coerce')

In [23]:
# Confirmo que no quedan filas con valores NA en la columna de id_clientes
df_sales['Id_cliente'].isna().sum()

np.int64(0)

In [24]:
# Uno los dos DataFrames en uno solo, usando la columna 'Id_cliente' como clave de unión.
df_unido = pd.merge(df_sales, df_customers, on='Id_cliente', how='inner')

df_unido

,Id_venta,Id_cliente,Fecha_venta,Importe,Producto,Cantidad,Descuento,Canal,Region,Estado,Zona_envio,Metodo_envio,Cantidad_num,Peso_paquete,Importe_num,Rango_valor_pedido,Coste_envio,Id_canal,Id_producto,Nombre,Correo,Telefono,Fecha_registro,Pais,Genero,Edad,Nivel_ingresos,Direccion,Ciudad,Provincia
0,S00001,1119,2015-04-13,252.44,widget i,4.0,20%,Retail,North,Pending,Zone 1,Local,4.0,6.0,252.44,Medium,11.7,Tienda3,PROD-009,Charlie Scott,charlie.scott@example.com,537-156-4153,2019/04/11,australia,Female,32.0,Low,1710 Cedar Ave,houston,TX
1,S00002,4149,2018-10-25,223.16,Widget F,8.0,15%,Mobile,East,Completed,Zone 3,Express,8.0,12.0,223.16,Medium,25.2,Tienda2,PROD-006,Quincy Allen,quincy.allen@example.com,447-652-2469,2016/04/15,USA,male,27.0,High,5360 Maple St,Toronto,BE
2,S00003,543,2017-07-22,985.37,Widget H,4.0,0.25,InStore,West,Pending,Zone 4,Pick-up,4.0,6.0,985.37,High,5.5,Tienda4,PROD-008,Michael Lee,michael.lee@exmaple.com,014-430-5699,2016/10/19,canada,Female,79.0,Unknown,7691 Elm St,Toronto,IL
3,S00004,4131,2015-08-18,41.78,Widget J,7.0,0.05,InStore,West,Shipped,Zone 4,Pick-up,7.0,10.5,41.78,Low,15.5,Tienda4,PROD-010,bob green,bob.green@example.com,(728) 335 7842,02/23/2016,USA,Male,37.0,low,8842 Maple St,Houston,ON
4,S00005,474,2016-07-20,$100.00,Widget B,10.0,0.15,Online,East,Cancelled,Zone 3,Standard,10.0,15.0,100.00,Medium,18.9,Tienda1,PROD-002,Grace Smith,grace.smith@example.com,(703) 547 6630,14-12-2019,Australia,NaN,NaN,High,1614 Cedar Ave,New York,TX
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54298,S05081,3259,2017-06-24,144.94,Widget H,6.0,0.15,mobile,east,Shipped,Zone 3,Express,6.0,9.0,144.94,Medium,22.5,Tienda2,PROD-008,Oscar Scott,oscar.scott@exmaple.com,398-930-9040,09/18/2019,Germany,Unknown,NaN,Low,7 Oak Ave,Sydney,fr
54299,S59170,4301,2018-01-07,39.08,Widget H,5.0,0.1,online,East,Shipped,Zone 3,Standard,5.0,7.5,39.08,Low,13.5,Tienda1,PROD-008,Bob Green,bob.green@example.com,(278) 764 2358,16-11-2019,USA,M,53.0,high,1937 Elm St,Paris,ENG
54300,S25974,1630,2019-05-15,72.11,Widget D,7.0,0.25,InStore,South,Cancelled,Zone 2,Pick-up,7.0,10.5,72.11,Low,14.5,Tienda4,PROD-004,John Wright,john.wright@example.com,NaN,20/06/2018,Spain,Female,74.0,High,9040 Birch Rd,Chicago,ENG
54301,S25520,3161,2022-01-03,893.5,widget b,8.0,30%,Mobile,East,Completed,Zone 3,Express,8.0,12.0,893.50,High,14.0,Tienda2,PROD-002,Eva Adams,eva.adams@example.com,841-843-6064,2016/06/18,Canada,Male,32.0,Low,812 Cedar Ave,Paris,IL
54302,S21800,3579,2022-10-27,49.51,Widget F,5.0,0.15,Retail,West,Pending,Zone 4,Local,5.0,7.5,49.51,Low,17.5,Tienda3,PROD-006,Alice Doe,alice.doe@example.com,141-298-0626,2015/03/10,Canada,F,46.0,high,9686 Maple St,Los Angeles,AZ

In [25]:
# Compruenbo si hay valores duplicados en la columna Id_venta del DataFrame unido
df_unido['Id_venta'].duplicated().sum()

np.int64(85)

In [26]:
# Elimino las filas con valores duplicados de la columna Id_venta, manteniendo solo los valores únicos.
df_sin_dups = df_unido[~df_unido['Id_venta'].duplicated(keep=False)]
df_sin_dups

,Id_venta,Id_cliente,Fecha_venta,Importe,Producto,Cantidad,Descuento,Canal,Region,Estado,Zona_envio,Metodo_envio,Cantidad_num,Peso_paquete,Importe_num,Rango_valor_pedido,Coste_envio,Id_canal,Id_producto,Nombre,Correo,Telefono,Fecha_registro,Pais,Genero,Edad,Nivel_ingresos,Direccion,Ciudad,Provincia
0,S00001,1119,2015-04-13,252.44,widget i,4.0,20%,Retail,North,Pending,Zone 1,Local,4.0,6.0,252.44,Medium,11.70,Tienda3,PROD-009,Charlie Scott,charlie.scott@example.com,537-156-4153,2019/04/11,australia,Female,32.0,Low,1710 Cedar Ave,houston,TX
1,S00002,4149,2018-10-25,223.16,Widget F,8.0,15%,Mobile,East,Completed,Zone 3,Express,8.0,12.0,223.16,Medium,25.20,Tienda2,PROD-006,Quincy Allen,quincy.allen@example.com,447-652-2469,2016/04/15,USA,male,27.0,High,5360 Maple St,Toronto,BE
2,S00003,543,2017-07-22,985.37,Widget H,4.0,0.25,InStore,West,Pending,Zone 4,Pick-up,4.0,6.0,985.37,High,5.50,Tienda4,PROD-008,Michael Lee,michael.lee@exmaple.com,014-430-5699,2016/10/19,canada,Female,79.0,Unknown,7691 Elm St,Toronto,IL
3,S00004,4131,2015-08-18,41.78,Widget J,7.0,0.05,InStore,West,Shipped,Zone 4,Pick-up,7.0,10.5,41.78,Low,15.50,Tienda4,PROD-010,bob green,bob.green@example.com,(728) 335 7842,02/23/2016,USA,Male,37.0,low,8842 Maple St,Houston,ON
4,S00005,474,2016-07-20,$100.00,Widget B,10.0,0.15,Online,East,Cancelled,Zone 3,Standard,10.0,15.0,100.00,Medium,18.90,Tienda1,PROD-002,Grace Smith,grace.smith@example.com,(703) 547 6630,14-12-2019,Australia,NaN,NaN,High,1614 Cedar Ave,New York,TX
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54213,S59993,1263,2021-04-26,551.34,Widget D,9.0,0.25,Online,north,Cancelled,Zone 1,Standard,9.0,13.5,551.34,High,9.25,Tienda1,PROD-004,Hannah Green,hannah.green@example.com,200-229-3905,2020-10-19,spain,male,55.0,high,2863 Maple St,London,BE
54214,S59994,573,2017-09-22,$365.14,Widget J,2.0,0.05,mobile,South,Pending,Zone 2,Express,2.0,3.0,365.14,Medium,18.00,Tienda2,PROD-010,Hannah White,hannah.white@example.com,(519) 676 4990,21-05-2015,France,F,73.0,Medium,5151 Pine Rd,London,AZ
54215,S59996,1615,2016-12-11,126.29,Widget E,5.0,0.1,Retail,North,Cancelled,Zone 1,Local,5.0,7.5,126.29,Medium,13.05,Tienda3,PROD-005,BOB HALL,NaN,176-751-6102,11-04-2021,Canada,Female,50.0,NaN,9004 Birch Rd,Madrid,ENG
54216,S59997,4603,2020-02-02,941.87,Widget H,9.0,0.05,Retail,West,Shipped,Zone 4,Local,9.0,13.5,941.87,High,11.75,Tienda3,PROD-008,Oscar Walker,oscar.walker@example.com,(187) 577 9321,17/11/2019,UK,F,56.0,medium,2729 Elm St,Houston,IL
54217,S59999,4448,2020-11-20,478.85,Widget H,8.0,0.25,Mobile,North,Cancelled,Zone 1,Express,8.0,12.0,478.85,Medium,24.30,Tienda2,PROD-008,Alice Wright,alice.wright@example.com,594-836-0901,12/03/2015,Germany,M,31.0,Unknown,9958 Elm St,new york,NY

In [27]:
# Reemplazo el df sin duplicados por el df_unido anterior, mediante una copia

df_unido = df_sin_dups.copy()

df_unido

,Id_venta,Id_cliente,Fecha_venta,Importe,Producto,Cantidad,Descuento,Canal,Region,Estado,Zona_envio,Metodo_envio,Cantidad_num,Peso_paquete,Importe_num,Rango_valor_pedido,Coste_envio,Id_canal,Id_producto,Nombre,Correo,Telefono,Fecha_registro,Pais,Genero,Edad,Nivel_ingresos,Direccion,Ciudad,Provincia
0,S00001,1119,2015-04-13,252.44,widget i,4.0,20%,Retail,North,Pending,Zone 1,Local,4.0,6.0,252.44,Medium,11.70,Tienda3,PROD-009,Charlie Scott,charlie.scott@example.com,537-156-4153,2019/04/11,australia,Female,32.0,Low,1710 Cedar Ave,houston,TX
1,S00002,4149,2018-10-25,223.16,Widget F,8.0,15%,Mobile,East,Completed,Zone 3,Express,8.0,12.0,223.16,Medium,25.20,Tienda2,PROD-006,Quincy Allen,quincy.allen@example.com,447-652-2469,2016/04/15,USA,male,27.0,High,5360 Maple St,Toronto,BE
2,S00003,543,2017-07-22,985.37,Widget H,4.0,0.25,InStore,West,Pending,Zone 4,Pick-up,4.0,6.0,985.37,High,5.50,Tienda4,PROD-008,Michael Lee,michael.lee@exmaple.com,014-430-5699,2016/10/19,canada,Female,79.0,Unknown,7691 Elm St,Toronto,IL
3,S00004,4131,2015-08-18,41.78,Widget J,7.0,0.05,InStore,West,Shipped,Zone 4,Pick-up,7.0,10.5,41.78,Low,15.50,Tienda4,PROD-010,bob green,bob.green@example.com,(728) 335 7842,02/23/2016,USA,Male,37.0,low,8842 Maple St,Houston,ON
4,S00005,474,2016-07-20,$100.00,Widget B,10.0,0.15,Online,East,Cancelled,Zone 3,Standard,10.0,15.0,100.00,Medium,18.90,Tienda1,PROD-002,Grace Smith,grace.smith@example.com,(703) 547 6630,14-12-2019,Australia,NaN,NaN,High,1614 Cedar Ave,New York,TX
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54213,S59993,1263,2021-04-26,551.34,Widget D,9.0,0.25,Online,north,Cancelled,Zone 1,Standard,9.0,13.5,551.34,High,9.25,Tienda1,PROD-004,Hannah Green,hannah.green@example.com,200-229-3905,2020-10-19,spain,male,55.0,high,2863 Maple St,London,BE
54214,S59994,573,2017-09-22,$365.14,Widget J,2.0,0.05,mobile,South,Pending,Zone 2,Express,2.0,3.0,365.14,Medium,18.00,Tienda2,PROD-010,Hannah White,hannah.white@example.com,(519) 676 4990,21-05-2015,France,F,73.0,Medium,5151 Pine Rd,London,AZ
54215,S59996,1615,2016-12-11,126.29,Widget E,5.0,0.1,Retail,North,Cancelled,Zone 1,Local,5.0,7.5,126.29,Medium,13.05,Tienda3,PROD-005,BOB HALL,NaN,176-751-6102,11-04-2021,Canada,Female,50.0,NaN,9004 Birch Rd,Madrid,ENG
54216,S59997,4603,2020-02-02,941.87,Widget H,9.0,0.05,Retail,West,Shipped,Zone 4,Local,9.0,13.5,941.87,High,11.75,Tienda3,PROD-008,Oscar Walker,oscar.walker@example.com,(187) 577 9321,17/11/2019,UK,F,56.0,medium,2729 Elm St,Houston,IL
54217,S59999,4448,2020-11-20,478.85,Widget H,8.0,0.25,Mobile,North,Cancelled,Zone 1,Express,8.0,12.0,478.85,Medium,24.30,Tienda2,PROD-008,Alice Wright,alice.wright@example.com,594-836-0901,12/03/2015,Germany,M,31.0,Unknown,9958 Elm St,new york,NY

In [28]:
#Compruebo que no quedan valores duplicados en Id_venta
df_unido['Id_venta'].duplicated().sum()

np.int64(0)

In [29]:
# Voy a cambiar la columna Id cliente por indice.

if 'Id_cliente' in df_unido.columns:
    df_unido = df_unido.set_index('Id_cliente')

df_unido.index.name = 'Id_cliente'
df_unido.head()

,Id_venta,Fecha_venta,Importe,Producto,Cantidad,Descuento,Canal,Region,Estado,Zona_envio,Metodo_envio,Cantidad_num,Peso_paquete,Importe_num,Rango_valor_pedido,Coste_envio,Id_canal,Id_producto,Nombre,Correo,Telefono,Fecha_registro,Pais,Genero,Edad,Nivel_ingresos,Direccion,Ciudad,Provincia
Id_cliente,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1119,S00001,2015-04-13,252.44,widget i,4.0,20%,Retail,North,Pending,Zone 1,Local,4.0,6.0,252.44,Medium,11.7,Tienda3,PROD-009,Charlie Scott,charlie.scott@example.com,537-156-4153,2019/04/11,australia,Female,32.0,Low,1710 Cedar Ave,houston,TX
4149,S00002,2018-10-25,223.16,Widget F,8.0,15%,Mobile,East,Completed,Zone 3,Express,8.0,12.0,223.16,Medium,25.2,Tienda2,PROD-006,Quincy Allen,quincy.allen@example.com,447-652-2469,2016/04/15,USA,male,27.0,High,5360 Maple St,Toronto,BE
543,S00003,2017-07-22,985.37,Widget H,4.0,0.25,InStore,West,Pending,Zone 4,Pick-up,4.0,6.0,985.37,High,5.5,Tienda4,PROD-008,Michael Lee,michael.lee@exmaple.com,014-430-5699,2016/10/19,canada,Female,79.0,Unknown,7691 Elm St,Toronto,IL
4131,S00004,2015-08-18,41.78,Widget J,7.0,0.05,InStore,West,Shipped,Zone 4,Pick-up,7.0,10.5,41.78,Low,15.5,Tienda4,PROD-010,bob green,bob.green@example.com,(728) 335 7842,02/23/2016,USA,Male,37.0,low,8842 Maple St,Houston,ON
474,S00005,2016-07-20,$100.00,Widget B,10.0,0.15,Online,East,Cancelled,Zone 3,Standard,10.0,15.0,100.00,Medium,18.9,Tienda1,PROD-002,Grace Smith,grace.smith@example.com,(703) 547 6630,14-12-2019,Australia,NaN,NaN,High,1614 Cedar Ave,New York,TX

In [30]:
# Ordeno de forma ascendente los id de clientes
df_unido = df_unido.sort_index()
df_unido.head()

,Id_venta,Fecha_venta,Importe,Producto,Cantidad,Descuento,Canal,Region,Estado,Zona_envio,Metodo_envio,Cantidad_num,Peso_paquete,Importe_num,Rango_valor_pedido,Coste_envio,Id_canal,Id_producto,Nombre,Correo,Telefono,Fecha_registro,Pais,Genero,Edad,Nivel_ingresos,Direccion,Ciudad,Provincia
Id_cliente,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,S16971,2017-05-31,214.46,Widget G,5.0,10%,Online,NaN,Cancelled,Unknown,Standard,5.0,7.5,214.46,Medium,15.75,Tienda1,PROD-007,Steve Brown,STEVE.BROWN@EXAMPLE.COM,(428) 039 4743,16-02-2017,Canada,M,50.0,Unknown,8534 Pine Rd,Phoenix,NY
1,S16302,2016-01-24,132.98,Widget H,5.0,0.1,Mobile,North,Shipped,Zone 1,Express,5.0,7.5,132.98,Medium,20.25,Tienda2,PROD-008,Steve Brown,STEVE.BROWN@EXAMPLE.COM,(428) 039 4743,16-02-2017,Canada,M,50.0,Unknown,8534 Pine Rd,Phoenix,NY
1,S33097,2016-04-05,253.95,Widget B,6.0,0.15,Online,West,Cancelled,Zone 4,Standard,6.0,9.0,253.95,Medium,15.30,Tienda1,PROD-002,Steve Brown,STEVE.BROWN@EXAMPLE.COM,(428) 039 4743,16-02-2017,Canada,M,50.0,Unknown,8534 Pine Rd,Phoenix,NY
1,S39629,2021-01-14,$348.60,Widget E,3.0,0%,Online,South,Pending,Zone 2,Standard,3.0,4.5,348.60,Medium,10.35,Tienda1,PROD-005,Steve Brown,STEVE.BROWN@EXAMPLE.COM,(428) 039 4743,16-02-2017,Canada,M,50.0,Unknown,8534 Pine Rd,Phoenix,NY
1,S37229,2015-11-07,652.46,Widget B,5.0,0.25,InStore,South,Completed,Zone 2,Pick-up,5.0,7.5,652.46,High,5.75,Tienda4,PROD-002,Steve Brown,STEVE.BROWN@EXAMPLE.COM,(428) 039 4743,16-02-2017,Canada,M,50.0,Unknown,8534 Pine Rd,Phoenix,NY

In [31]:
# Reviso los valores de ciudad y elimino espacios. 
df_unido['Ciudad'] = df_unido['Ciudad'].str.strip().str.title()

In [32]:
# Creo un diccionario para mapear las ciudades a sus respectivos países
map_ciudad_pais = {
    'Toronto': 'Canada',
    'Berlin': 'Alemania',
    'Chicago': 'EE.UU',
    'Paris': 'Francia',
    'Phoenix': 'EE.UU',
    'London': 'Reino Unido',
    'Madrid': 'España',
    'Houston': 'EE.UU',
    'Sydney': 'Australia',
    'New York': 'EE.UU',
    'Los Angeles': 'EE.UU',
}

In [33]:
# Creo una máscara booleana para identificar las filas donde la ciudad está en el diccionario
mask = df_unido['Ciudad'].isin(map_ciudad_pais.keys())

df_unido.loc[mask, 'Pais'] = df_unido.loc[mask, 'Ciudad'].map(map_ciudad_pais)

In [34]:
# Reviso las filas donde la ciudad está en el diccionario y muestro las columnas 'Ciudad' y 'Pais'
df_unido.loc[df_unido['Ciudad'].isin(map_ciudad_pais.keys()), ['Ciudad', 'Pais']]

             Ciudad         Pais
Id_cliente
1           Phoenix        EE.UU
1           Phoenix        EE.UU
1           Phoenix        EE.UU
1           Phoenix        EE.UU
1           Phoenix        EE.UU
...             ...          ...
5000         London  Reino Unido
5000         London  Reino Unido
5000         London  Reino Unido
5000         London  Reino Unido
5000         London  Reino Unido

[54133 rows x 2 columns]

In [35]:
# Compruebo si hay valores NA en la columna 'Pais' después de mapear las ciudades
df_unido['Pais'].isna().sum()

np.int64(0)

In [36]:
# Reviso que cada ciudad tenga asociada su pais correspondoente 
df_unido.loc[:, ['Ciudad', 'Pais']].drop_duplicates().sort_values('Ciudad')

                 Ciudad         Pais
Id_cliente
3                Berlin     Alemania
9               Chicago        EE.UU
38              Houston        EE.UU
15               London  Reino Unido
14          Los Angeles        EE.UU
7                Madrid       España
8              New York        EE.UU
13                Paris      Francia
1               Phoenix        EE.UU
40               Sydney    Australia
2               Toronto       Canada

In [37]:
# Compruebo que no hay ciudades asignadas a mas de 1 páis
df_unido.groupby('Ciudad')['Pais'].nunique().sort_values(ascending=False)

Ciudad
Berlin         1
Chicago        1
Houston        1
London         1
Los Angeles    1
Madrid         1
New York       1
Paris          1
Phoenix        1
Sydney         1
Toronto        1
Name: Pais, dtype: int64

In [38]:
df_unido

,Id_venta,Fecha_venta,Importe,Producto,Cantidad,Descuento,Canal,Region,Estado,Zona_envio,Metodo_envio,Cantidad_num,Peso_paquete,Importe_num,Rango_valor_pedido,Coste_envio,Id_canal,Id_producto,Nombre,Correo,Telefono,Fecha_registro,Pais,Genero,Edad,Nivel_ingresos,Direccion,Ciudad,Provincia
Id_cliente,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,S16971,2017-05-31,214.46,Widget G,5.0,10%,Online,NaN,Cancelled,Unknown,Standard,5.0,7.5,214.46,Medium,15.75,Tienda1,PROD-007,Steve Brown,STEVE.BROWN@EXAMPLE.COM,(428) 039 4743,16-02-2017,EE.UU,M,50.0,Unknown,8534 Pine Rd,Phoenix,NY
1,S16302,2016-01-24,132.98,Widget H,5.0,0.1,Mobile,North,Shipped,Zone 1,Express,5.0,7.5,132.98,Medium,20.25,Tienda2,PROD-008,Steve Brown,STEVE.BROWN@EXAMPLE.COM,(428) 039 4743,16-02-2017,EE.UU,M,50.0,Unknown,8534 Pine Rd,Phoenix,NY
1,S33097,2016-04-05,253.95,Widget B,6.0,0.15,Online,West,Cancelled,Zone 4,Standard,6.0,9.0,253.95,Medium,15.30,Tienda1,PROD-002,Steve Brown,STEVE.BROWN@EXAMPLE.COM,(428) 039 4743,16-02-2017,EE.UU,M,50.0,Unknown,8534 Pine Rd,Phoenix,NY
1,S39629,2021-01-14,$348.60,Widget E,3.0,0%,Online,South,Pending,Zone 2,Standard,3.0,4.5,348.60,Medium,10.35,Tienda1,PROD-005,Steve Brown,STEVE.BROWN@EXAMPLE.COM,(428) 039 4743,16-02-2017,EE.UU,M,50.0,Unknown,8534 Pine Rd,Phoenix,NY
1,S37229,2015-11-07,652.46,Widget B,5.0,0.25,InStore,South,Completed,Zone 2,Pick-up,5.0,7.5,652.46,High,5.75,Tienda4,PROD-002,Steve Brown,STEVE.BROWN@EXAMPLE.COM,(428) 039 4743,16-02-2017,EE.UU,M,50.0,Unknown,8534 Pine Rd,Phoenix,NY
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5000,S43959,2017-05-16,249.36,Widget G,3.0,0.2,Online,South,Pending,Zone 2,Standard,3.0,4.5,249.36,Medium,10.35,Tienda1,PROD-007,JOHN ROBINSON,john.robinson@example.com,053-325-6001,23/09/2017,Reino Unido,Unknown,49.0,low,5014 Maple St,London,TX
5000,S48825,2016-06-21,639.67,Widget C,7.0,NaN,Retail,South,Completed,Zone 2,Local,7.0,10.5,639.67,High,9.75,Tienda3,PROD-003,JOHN ROBINSON,john.robinson@example.com,053-325-6001,23/09/2017,Reino Unido,Unknown,49.0,low,5014 Maple St,London,TX
5000,S49648,2016-08-03,898.22,Widget E,5.0,0.25,Retail,North,Shipped,Zone 1,Local,5.0,7.5,898.22,High,7.25,Tienda3,PROD-005,JOHN ROBINSON,john.robinson@example.com,053-325-6001,23/09/2017,Reino Unido,Unknown,49.0,low,5014 Maple St,London,TX
5000,S38648,2019-04-23,328.66,Widget D,10.0,0.05,Retail,north,Shipped,Zone 1,Local,10.0,15.0,328.66,Medium,19.80,Tienda3,PROD-004,JOHN ROBINSON,john.robinson@example.com,053-325-6001,23/09/2017,Reino Unido,Unknown,49.0,low,5014 Maple St,London,TX
5000,S08148,2017-03-03,$260.82,Widget I,7.0,5%,Online,West,Pending,Zone 4,Standard,7.0,10.5,260.82,Medium,16.65,Tienda1,PROD-009,JOHN ROBINSON,john.robinson@example.com,053-325-6001,23/09/2017,Reino Unido,Unknown,49.0,low,5014 Maple St,London,TX

In [39]:
# Elimino las columnas 'Provincia','Direccion','Telefono','Correo','Cantidad_num'

df_unido.drop(columns=['Provincia','Direccion','Telefono','Correo','Cantidad_num'], inplace=True)

In [40]:
df_unido

,Id_venta,Fecha_venta,Importe,Producto,Cantidad,Descuento,Canal,Region,Estado,Zona_envio,Metodo_envio,Peso_paquete,Importe_num,Rango_valor_pedido,Coste_envio,Id_canal,Id_producto,Nombre,Fecha_registro,Pais,Genero,Edad,Nivel_ingresos,Ciudad
Id_cliente,,,,,,,,,,,,,,,,,,,,,,,,
1,S16971,2017-05-31,214.46,Widget G,5.0,10%,Online,NaN,Cancelled,Unknown,Standard,7.5,214.46,Medium,15.75,Tienda1,PROD-007,Steve Brown,16-02-2017,EE.UU,M,50.0,Unknown,Phoenix
1,S16302,2016-01-24,132.98,Widget H,5.0,0.1,Mobile,North,Shipped,Zone 1,Express,7.5,132.98,Medium,20.25,Tienda2,PROD-008,Steve Brown,16-02-2017,EE.UU,M,50.0,Unknown,Phoenix
1,S33097,2016-04-05,253.95,Widget B,6.0,0.15,Online,West,Cancelled,Zone 4,Standard,9.0,253.95,Medium,15.30,Tienda1,PROD-002,Steve Brown,16-02-2017,EE.UU,M,50.0,Unknown,Phoenix
1,S39629,2021-01-14,$348.60,Widget E,3.0,0%,Online,South,Pending,Zone 2,Standard,4.5,348.60,Medium,10.35,Tienda1,PROD-005,Steve Brown,16-02-2017,EE.UU,M,50.0,Unknown,Phoenix
1,S37229,2015-11-07,652.46,Widget B,5.0,0.25,InStore,South,Completed,Zone 2,Pick-up,7.5,652.46,High,5.75,Tienda4,PROD-002,Steve Brown,16-02-2017,EE.UU,M,50.0,Unknown,Phoenix
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5000,S43959,2017-05-16,249.36,Widget G,3.0,0.2,Online,South,Pending,Zone 2,Standard,4.5,249.36,Medium,10.35,Tienda1,PROD-007,JOHN ROBINSON,23/09/2017,Reino Unido,Unknown,49.0,low,London
5000,S48825,2016-06-21,639.67,Widget C,7.0,NaN,Retail,South,Completed,Zone 2,Local,10.5,639.67,High,9.75,Tienda3,PROD-003,JOHN ROBINSON,23/09/2017,Reino Unido,Unknown,49.0,low,London
5000,S49648,2016-08-03,898.22,Widget E,5.0,0.25,Retail,North,Shipped,Zone 1,Local,7.5,898.22,High,7.25,Tienda3,PROD-005,JOHN ROBINSON,23/09/2017,Reino Unido,Unknown,49.0,low,London
5000,S38648,2019-04-23,328.66,Widget D,10.0,0.05,Retail,north,Shipped,Zone 1,Local,15.0,328.66,Medium,19.80,Tienda3,PROD-004,JOHN ROBINSON,23/09/2017,Reino Unido,Unknown,49.0,low,London
5000,S08148,2017-03-03,$260.82,Widget I,7.0,5%,Online,West,Pending,Zone 4,Standard,10.5,260.82,Medium,16.65,Tienda1,PROD-009,JOHN ROBINSON,23/09/2017,Reino Unido,Unknown,49.0,low,London

In [41]:
# Reemplazar Widget por Dispositivo en el valor de la columna Producto, sin importar mayusculas o minusculas
df_unido['Producto'] = (
    df_unido['Producto']
    .astype('string')
    .str.replace(r'(?i)\bwidget\b', 'Dispositivo', regex=True)
)

In [42]:
# Cambio la letra del producto Dispositivo en mayusculas
df_unido['Producto'] = (
    df_unido['Producto']
    .astype('string')
    .str.replace(
        r'(?i)dispositivo\s([a-z])',
        lambda m: 'Dispositivo ' + m.group(1).upper(),
        regex=True
    )
)

In [43]:
# Reviso si hay valores duplicados 
sorted(df_unido['Producto'].unique())

['Dispositivo A',
 'Dispositivo A ',
 'Dispositivo B',
 'Dispositivo B ',
 'Dispositivo C',
 'Dispositivo C ',
 'Dispositivo D',
 'Dispositivo D ',
 'Dispositivo E',
 'Dispositivo E ',
 'Dispositivo F',
 'Dispositivo F ',
 'Dispositivo G',
 'Dispositivo G ',
 'Dispositivo H',
 'Dispositivo H ',
 'Dispositivo I',
 'Dispositivo I ',
 'Dispositivo J',
 'Dispositivo J ']

In [44]:
# Limpio los datos con espacios 
df_unido['Producto'] = (
    df_unido['Producto']
    .astype(str)
    .str.strip()
)

In [45]:
# Reviso el resultado si quedan valores duplicados 
sorted(df_unido['Producto'].unique())

['Dispositivo A',
 'Dispositivo B',
 'Dispositivo C',
 'Dispositivo D',
 'Dispositivo E',
 'Dispositivo F',
 'Dispositivo G',
 'Dispositivo H',
 'Dispositivo I',
 'Dispositivo J']

In [46]:
# Voy a convertir los datos de Canal en español. Para ello, reviso como estan los datos originales
df_unido['Canal'].unique()

<StringArray>
[ 'Online',  'Mobile', 'InStore',  'retail',  'Retail', 'instore',  'online',
  'mobile']
Length: 8, dtype: str

In [47]:

# Los normalizo a minisculas, elimno espacios internos, externos
df_unido['Canal'] = (
    df_unido['Canal']
    .str.strip()          
    .str.lower()          
    .str.replace(' ', '') 
)

In [48]:
# Los reemplazo por mayusculas
df_unido['Canal'] = df_unido['Canal'].replace({
    'retail': 'Retail',
    'mobile': 'Mobile',
    'instore': 'InStore',
    'online': 'Online'
})

In [49]:
# Creo un diccionario con las palabras traducidas a español

map_canal_es = {
    'Retail': 'Minorista',
    'Mobile': 'M-Commerce',
    'InStore': 'En Tienda',
    'Online': 'En Linea'
}

In [50]:
# los meto mediante .map en la columna Canal
df_unido['Canal'] = df_unido['Canal'].map(map_canal_es)

In [51]:
# Compruebo que totos los valores estan traducidos y no hay valores nan
df_unido['Canal'].unique()

<StringArray>
['En Linea', 'M-Commerce', 'En Tienda', 'Minorista']
Length: 4, dtype: str

In [52]:
df_unido

,Id_venta,Fecha_venta,Importe,Producto,Cantidad,Descuento,Canal,Region,Estado,Zona_envio,Metodo_envio,Peso_paquete,Importe_num,Rango_valor_pedido,Coste_envio,Id_canal,Id_producto,Nombre,Fecha_registro,Pais,Genero,Edad,Nivel_ingresos,Ciudad
Id_cliente,,,,,,,,,,,,,,,,,,,,,,,,
1,S16971,2017-05-31,214.46,Dispositivo G,5.0,10%,En Linea,NaN,Cancelled,Unknown,Standard,7.5,214.46,Medium,15.75,Tienda1,PROD-007,Steve Brown,16-02-2017,EE.UU,M,50.0,Unknown,Phoenix
1,S16302,2016-01-24,132.98,Dispositivo H,5.0,0.1,M-Commerce,North,Shipped,Zone 1,Express,7.5,132.98,Medium,20.25,Tienda2,PROD-008,Steve Brown,16-02-2017,EE.UU,M,50.0,Unknown,Phoenix
1,S33097,2016-04-05,253.95,Dispositivo B,6.0,0.15,En Linea,West,Cancelled,Zone 4,Standard,9.0,253.95,Medium,15.30,Tienda1,PROD-002,Steve Brown,16-02-2017,EE.UU,M,50.0,Unknown,Phoenix
1,S39629,2021-01-14,$348.60,Dispositivo E,3.0,0%,En Linea,South,Pending,Zone 2,Standard,4.5,348.60,Medium,10.35,Tienda1,PROD-005,Steve Brown,16-02-2017,EE.UU,M,50.0,Unknown,Phoenix
1,S37229,2015-11-07,652.46,Dispositivo B,5.0,0.25,En Tienda,South,Completed,Zone 2,Pick-up,7.5,652.46,High,5.75,Tienda4,PROD-002,Steve Brown,16-02-2017,EE.UU,M,50.0,Unknown,Phoenix
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5000,S43959,2017-05-16,249.36,Dispositivo G,3.0,0.2,En Linea,South,Pending,Zone 2,Standard,4.5,249.36,Medium,10.35,Tienda1,PROD-007,JOHN ROBINSON,23/09/2017,Reino Unido,Unknown,49.0,low,London
5000,S48825,2016-06-21,639.67,Dispositivo C,7.0,NaN,Minorista,South,Completed,Zone 2,Local,10.5,639.67,High,9.75,Tienda3,PROD-003,JOHN ROBINSON,23/09/2017,Reino Unido,Unknown,49.0,low,London
5000,S49648,2016-08-03,898.22,Dispositivo E,5.0,0.25,Minorista,North,Shipped,Zone 1,Local,7.5,898.22,High,7.25,Tienda3,PROD-005,JOHN ROBINSON,23/09/2017,Reino Unido,Unknown,49.0,low,London
5000,S38648,2019-04-23,328.66,Dispositivo D,10.0,0.05,Minorista,north,Shipped,Zone 1,Local,15.0,328.66,Medium,19.80,Tienda3,PROD-004,JOHN ROBINSON,23/09/2017,Reino Unido,Unknown,49.0,low,London
5000,S08148,2017-03-03,$260.82,Dispositivo I,7.0,5%,En Linea,West,Pending,Zone 4,Standard,10.5,260.82,Medium,16.65,Tienda1,PROD-009,JOHN ROBINSON,23/09/2017,Reino Unido,Unknown,49.0,low,London

In [53]:
df_unido.info()

<class 'pandas.DataFrame'>
Index: 54133 entries, 1 to 5000
Data columns (total 24 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Id_venta            54133 non-null  object
 1   Fecha_venta         53585 non-null  str
 2   Importe             52899 non-null  str
 3   Producto            54133 non-null  str
 4   Cantidad            52985 non-null  float64
 5   Descuento           51436 non-null  str
 6   Canal               54133 non-null  str
 7   Region              51400 non-null  str
 8   Estado              54133 non-null  str
 9   Zona_envio          54133 non-null  str
 10  Metodo_envio        54133 non-null  str
 11  Peso_paquete        54133 non-null  float64
 12  Importe_num         52899 non-null  float64
 13  Rango_valor_pedido  54133 non-null  str
 14  Coste_envio         54133 non-null  float64
 15  Id_canal            54133 non-null  str
 16  Id_producto         54133 non-null  str
 17  Nombre              54133 non-null  str
 18  Fecha_registro      53079 non-null  str
 19  Pais                54133 non-null  str
 20  Genero              51723 non-null  str
 21  Edad                51357 non-null  float64
 22  Nivel_ingresos      51354 non-null  str
 23  Ciudad              54133 non-null  str
dtypes: float64(5), object(1), str(18)
memory usage: 10.4+ MB

In [54]:
df_unido

,Id_venta,Fecha_venta,Importe,Producto,Cantidad,Descuento,Canal,Region,Estado,Zona_envio,Metodo_envio,Peso_paquete,Importe_num,Rango_valor_pedido,Coste_envio,Id_canal,Id_producto,Nombre,Fecha_registro,Pais,Genero,Edad,Nivel_ingresos,Ciudad
Id_cliente,,,,,,,,,,,,,,,,,,,,,,,,
1,S16971,2017-05-31,214.46,Dispositivo G,5.0,10%,En Linea,NaN,Cancelled,Unknown,Standard,7.5,214.46,Medium,15.75,Tienda1,PROD-007,Steve Brown,16-02-2017,EE.UU,M,50.0,Unknown,Phoenix
1,S16302,2016-01-24,132.98,Dispositivo H,5.0,0.1,M-Commerce,North,Shipped,Zone 1,Express,7.5,132.98,Medium,20.25,Tienda2,PROD-008,Steve Brown,16-02-2017,EE.UU,M,50.0,Unknown,Phoenix
1,S33097,2016-04-05,253.95,Dispositivo B,6.0,0.15,En Linea,West,Cancelled,Zone 4,Standard,9.0,253.95,Medium,15.30,Tienda1,PROD-002,Steve Brown,16-02-2017,EE.UU,M,50.0,Unknown,Phoenix
1,S39629,2021-01-14,$348.60,Dispositivo E,3.0,0%,En Linea,South,Pending,Zone 2,Standard,4.5,348.60,Medium,10.35,Tienda1,PROD-005,Steve Brown,16-02-2017,EE.UU,M,50.0,Unknown,Phoenix
1,S37229,2015-11-07,652.46,Dispositivo B,5.0,0.25,En Tienda,South,Completed,Zone 2,Pick-up,7.5,652.46,High,5.75,Tienda4,PROD-002,Steve Brown,16-02-2017,EE.UU,M,50.0,Unknown,Phoenix
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5000,S43959,2017-05-16,249.36,Dispositivo G,3.0,0.2,En Linea,South,Pending,Zone 2,Standard,4.5,249.36,Medium,10.35,Tienda1,PROD-007,JOHN ROBINSON,23/09/2017,Reino Unido,Unknown,49.0,low,London
5000,S48825,2016-06-21,639.67,Dispositivo C,7.0,NaN,Minorista,South,Completed,Zone 2,Local,10.5,639.67,High,9.75,Tienda3,PROD-003,JOHN ROBINSON,23/09/2017,Reino Unido,Unknown,49.0,low,London
5000,S49648,2016-08-03,898.22,Dispositivo E,5.0,0.25,Minorista,North,Shipped,Zone 1,Local,7.5,898.22,High,7.25,Tienda3,PROD-005,JOHN ROBINSON,23/09/2017,Reino Unido,Unknown,49.0,low,London
5000,S38648,2019-04-23,328.66,Dispositivo D,10.0,0.05,Minorista,north,Shipped,Zone 1,Local,15.0,328.66,Medium,19.80,Tienda3,PROD-004,JOHN ROBINSON,23/09/2017,Reino Unido,Unknown,49.0,low,London
5000,S08148,2017-03-03,$260.82,Dispositivo I,7.0,5%,En Linea,West,Pending,Zone 4,Standard,10.5,260.82,Medium,16.65,Tienda1,PROD-009,JOHN ROBINSON,23/09/2017,Reino Unido,Unknown,49.0,low,London

In [55]:

# Tratamiento y normalización de valores de Importe. Limpieza de espacios, caracteres raros, comas por puntos
df_unido['Importe'] = (
    df_unido['Importe']
    .astype(str)
    .str.strip()
    .str.replace(r'[$€]', '', regex=True)      
    .str.replace(r'[A-Za-z]', '', regex=True)  
    .str.replace(' ', '')                      
    .str.replace(r'\.(?=.*\.)', '', regex=True) 
    .str.replace(',', '.', regex=False)        
)

In [56]:
# Convierto valores a numericos con un máximo de 2 decimales y elimino los valores que no se puedan convertir a numericos
df_unido['Importe'] = pd.to_numeric(df_unido['Importe'], errors='coerce')
df_unido = df_unido.dropna(subset=['Importe'])
df_unido['Importe'] = df_unido['Importe'].round(2)

In [57]:
df_unido['Importe'].head()
df_unido['Importe'].dtype

dtype('float64')

In [58]:
df_unido['Importe'].isna().sum()

np.int64(0)

In [59]:
# Relleno valores NA de la columna Importe con la media de la columna
df_unido['Importe'] = df_unido['Importe'].fillna(df_unido['Importe'].mean())

In [60]:
# Relleno valores NA de la columna Cantidad con la media de la columna
df_unido['Cantidad'] = df_unido['Cantidad'].fillna(df_unido['Cantidad'].mean())

In [61]:
# Relleno valores NA de la columna Descuento con la media de la columna
col = 'Descuento'
df_unido[col] = (
    df_unido[col]
    .astype(str)
    .str.strip()
    .str.replace('%', '', regex=False)
    .str.replace(',', '.', regex=False)
)
df_unido[col] = pd.to_numeric(df_unido[col], errors='coerce')
df_unido[col] = df_unido[col].fillna(df_unido[col].mean())

In [62]:
# Relleno valores NA de la columna Edad con la media de la columna
df_unido['Edad'] = df_unido['Edad'].fillna(df_unido['Edad'].mean())

In [63]:
df_unido.isna().sum()

Id_venta                 0
Fecha_venta            536
Importe                  0
Producto                 0
Cantidad                 0
Descuento                0
Canal                    0
Region                2675
Estado                   0
Zona_envio               0
Metodo_envio             0
Peso_paquete             0
Importe_num              0
Rango_valor_pedido       0
Coste_envio              0
Id_canal                 0
Id_producto              0
Nombre                   0
Fecha_registro        1031
Pais                     0
Genero                2351
Edad                     0
Nivel_ingresos        2722
Ciudad                   0
dtype: int64

In [64]:
# Reviso valores duplicados en todas las columnas del DataFrame
df_unido.apply(lambda col: col.duplicated().sum())

Id_venta                  0
Fecha_venta           49976
Importe               11904
Producto              52889
Cantidad              52888
Descuento             52885
Canal                 52895
Region                52890
Estado                52895
Zona_envio            52894
Metodo_envio          52895
Peso_paquete          52889
Importe_num           11904
Rango_valor_pedido    52896
Coste_envio           52756
Id_canal              52895
Id_producto           52889
Nombre                51678
Fecha_registro        48932
Pais                  52892
Genero                52891
Edad                  52835
Nivel_ingresos        52882
Ciudad                52888
dtype: int64

In [65]:
# Compruebo valores en el fichero de origen y los convierto a string en una nueva columna
df_unido['Fecha_registro_raw'] = df_unido['Fecha_registro'].astype(str)

In [66]:
# Tratamiento y normalización de valores en Fecha_registro segun el fichero original
df_unido['Fecha_registro'] = (
    df_unido['Fecha_registro_raw']
    .str.strip()
    .str.replace(' ', '')
    .str.replace(r'[^0-9A-Za-z/-]', '', regex=True) 
)

In [67]:
# Convertir a fecha con formato mixto
df_unido['Fecha_registro'] = pd.to_datetime(
    df_unido['Fecha_registro'],
    errors='coerce',
    dayfirst=True,
    format='mixed'
)

In [68]:
# Elimino filas de Fecha_venta y Fecha_registro con valores NA
df_unido = df_unido[df_unido['Fecha_venta'].notna()]
df_unido = df_unido[df_unido['Fecha_registro'].notna()]

In [69]:
# Relleno valores de Fecha venta con los valores de Fecha registro
df_unido['Fecha_venta'] = df_unido['Fecha_venta'].fillna(df_unido['Fecha_registro'])

In [70]:
# Relleno valores faltantes de Fecha_registro con los valores de Fecha_venta
df_unido['Fecha_registro'] = df_unido['Fecha_registro'].fillna(df_unido['Fecha_venta'])

In [71]:
# Convierto los valores de Fecha_venta a formato dd/mm/yyyy
df_unido['Fecha_venta'] = pd.to_datetime(df_unido['Fecha_venta'], errors='coerce', dayfirst=True)
df_unido['Fecha_venta'] = df_unido['Fecha_venta'].dt.strftime('%d/%m/%Y')

C:\Users\dgjer\AppData\Local\Temp\ipykernel_8016\936800753.py:2: UserWarning: Parsing dates in %Y-%m-%d format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  df_unido['Fecha_venta'] = pd.to_datetime(df_unido['Fecha_venta'], errors='coerce', dayfirst=True)

In [72]:
# Convierto los valores de Fecha_registro a formato dd/mm/yyyy
df_unido['Fecha_registro'] = pd.to_datetime(df_unido['Fecha_registro'], errors='coerce', dayfirst=True)
df_unido['Fecha_registro'] = df_unido['Fecha_registro'].dt.strftime('%d/%m/%Y')

In [73]:
# Elimino las columnas RAW e Importe_num
df_unido.drop(columns=['Fecha_registro_raw', 'Importe_num'], inplace=True, errors='ignore')

In [74]:
# Tratamiento de valores de Descuento. Limpieza espacios y conversión de string a float

df_unido['Descuento'] = (
    df_unido['Descuento']
    .astype(str)
    .str.strip()
    .str.replace('%', '', regex=False)
    .str.replace(' ', '', regex=False)
    .str.replace(',', '.', regex=False)
)
df_unido['Descuento'] = pd.to_numeric(df_unido['Descuento'], errors='coerce')
df_unido['Descuento'] = df_unido['Descuento'].round().astype('float64')

In [75]:
# Tratamiento y limpieza de valores Cantidad. Convertir valores de Cantidad de float a entero
df_unido['Cantidad'] = (
    pd.to_numeric(
        df_unido['Cantidad'].astype(str).str.strip().str.replace(',', '.', regex=False),
        errors='coerce'
    )
)
df_unido['Cantidad'] = df_unido['Cantidad'].round().astype('Int64')

In [76]:

# Convertir valores de Edad de float a entero
df_unido['Edad'] = pd.to_numeric(df_unido['Edad'], errors='coerce')
df_unido['Edad'] = df_unido['Edad'].round().astype('Int64')

In [77]:
# Reemplazo valores NA en las columnas Region, Genero, Nivel_ingresos por el valor 'Desconocido'.
df_unido[['Region', 'Genero', 'Nivel_ingresos']] = df_unido[['Region', 'Genero', 'Nivel_ingresos']].fillna('Desconocido')

In [78]:
# Reemplacar valores Unknwoun por Desconocido
df_unido['Nivel_ingresos'] = (
    df_unido['Nivel_ingresos']
    .astype(str)
    .str.strip()
    .replace({'Unknown': 'Desconocido',
              'unknown': 'Desconocido',
              'Unknwon': 'Desconocido'})
)

df_unido['Rango_valor_pedido'] = (
    df_unido['Rango_valor_pedido']
    .astype(str)
    .str.strip()
    .replace({'Unknown': 'Desconocido',
              'unknown': 'Desconocido',
              'Unknwon': 'Desconocido'})
)

df_unido['Genero'] = (
    df_unido['Genero']
    .astype(str)
    .str.strip()
    .replace({'Unknown': 'Desconocido',
              'unknown': 'Desconocido',
              'Unknwon': 'Desconocido'})
)

df_unido['Zona_envio'] = (
    df_unido['Zona_envio']
    .astype(str)
    .str.strip()
    .replace({'Unknown': 'Desconocido',
              'unknown': 'Desconocido',
              'Unknwon': 'Desconocido'})
)

In [79]:
df_unido['Nivel_ingresos'].unique()
df_unido['Rango_valor_pedido'].unique()

<StringArray>
['Medium', 'High', 'Low']
Length: 3, dtype: str

In [80]:
# Voy a convertir los datos de Genero en español. Para ello, reviso como estan los datos originales
df_unido['Genero'].unique()

<StringArray>
['M', 'Desconocido', 'female', 'male', 'Male', 'Female', 'F']
Length: 7, dtype: str

In [81]:
# Reemplazo valores por su equivalente en español
df_unido['Genero'] = (
    df_unido['Genero']
    .astype(str)
    .str.strip()
    .replace({'M': 'Hombre',
              'male': 'Hombre',
              'Male': 'Hombre',
              'F': 'Mujer',
              'Female': 'Mujer',
              'female': 'Mujer'})
)

In [82]:
df_unido['Genero'].unique()

<StringArray>
['Hombre', 'Desconocido', 'Mujer']
Length: 3, dtype: str

In [83]:
# Voy a convertir los datos de Nivel_ingresos en español. Para ello, reviso como estan los datos originales
df_unido['Nivel_ingresos'].unique()

<StringArray>
['Desconocido', 'low', 'Low', 'high', 'High', 'medium', 'Medium']
Length: 7, dtype: str

In [84]:
# Reemplazo valores por su equivalente en español
df_unido['Nivel_ingresos'] = (
    df_unido['Nivel_ingresos']
    .astype(str)
    .str.strip()
    .replace({'Low': 'Bajo',
              'low': 'Bajo',
              'High': 'Alto',
              'high': 'Alto',
              'Medium': 'Medio',
              'medium': 'Medio'})
)

In [85]:
df_unido['Nivel_ingresos'].unique()

<StringArray>
['Desconocido', 'Bajo', 'Alto', 'Medio']
Length: 4, dtype: str

In [86]:
# Voy a convertir los datos de Rango_valor_pedodo en español. Para ello, reviso como estan los datos originales
df_unido['Rango_valor_pedido'].unique()

<StringArray>
['Medium', 'High', 'Low']
Length: 3, dtype: str

In [87]:
# Reemplazo valores por su equivalente en español
df_unido['Rango_valor_pedido'] = (
    df_unido['Rango_valor_pedido']
    .astype(str)
    .str.strip()
    .replace({'Low': 'Bajo',
              'High': 'Alto',
              'Medium': 'Medio',
              })
)

In [88]:
df_unido['Rango_valor_pedido'].unique()

<StringArray>
['Medio', 'Alto', 'Bajo']
Length: 3, dtype: str

In [89]:
# Tratamiento de valores Desconocido en el Genero.
# Reviso los valores de Nombre cuyo Genero es Desconocido

df_genero_desconocido = df_unido[df_unido['Genero'] == 'Desconocido'][['Genero', 'Nombre']]
df_genero_desconocido.head(10)

                 Genero        Nombre
Id_cliente
3           Desconocido   John Lewis
3           Desconocido   John Lewis
3           Desconocido   John Lewis
3           Desconocido   John Lewis
3           Desconocido   John Lewis
3           Desconocido   John Lewis
3           Desconocido   John Lewis
3           Desconocido   John Lewis
3           Desconocido   John Lewis
3           Desconocido   John Lewis

In [90]:
# Normalizo los nombres en maysculas y minusculas

df_unido['Nombre_normalizado'] = df_unido['Nombre'].str.title()

In [91]:
# Creo un diccionario de nombres masculinos y femeninos para asignar el genero a los nombres desconocidos
male_names = [
    'John','Michael','Charlie','David','James','Robert','William','Richard','Thomas','Charles','Daniel',
    'Matthew','Anthony','Mark','Paul','Steven','Andrew','Joshua','Kevin','Brian','George',
    'Frank','Oscar','Jack','Steve','Bob','Quincy'
]

female_names = [
    'Mary','Patricia','Jennifer','Linda','Elizabeth','Barbara','Susan','Jessica','Sarah','Karen',
    'Nancy','Lisa','Margaret','Betty','Sandra','Ashley','Kimberly','Emily','Donna','Michelle',
    'Grace','Eva','Jane','Alice','Laura','Hannah','Irene','Nina','Rachel'
]

In [92]:
# Creo una función para cambiar nombres del dicionaroo a generos 'Hombre' y 'Mujer'.
def gender_from_dict(name):
    first = name.split()[0].capitalize()
    if first in male_names:
        return 'Hombre'
    if first in female_names:
        return 'Mujer'
    return 'Desconocido'

In [93]:
# Aplico la función gender_from_dict a los nombres desconocidos para asignarles un genero basado en el diccionario
df_unido.loc[df_unido['Genero'] == 'Desconocido', 'Genero'] = \
    df_unido.loc[df_unido['Genero'] == 'Desconocido', 'Nombre_normalizado'].apply(gender_from_dict)

In [94]:
df_unido[['Nombre', 'Genero']].head()

                 Nombre  Genero
Id_cliente
1           Steve Brown  Hombre
1           Steve Brown  Hombre
1           Steve Brown  Hombre
1           Steve Brown  Hombre
1           Steve Brown  Hombre

In [95]:
# Elimino la columna Nombre_normalizado

df_unido.drop(columns=['Nombre_normalizado'], inplace=True)

In [96]:
# Compruebo que no quedan valores Desconocido en la columna Genero
df_unido[df_unido['Genero'] == 'Desconocido']

Empty DataFrame
Columns: [Id_venta, Fecha_venta, Importe, Producto, Cantidad, Descuento, Canal, Region, Estado, Zona_envio, Metodo_envio, Peso_paquete, Rango_valor_pedido, Coste_envio, Id_canal, Id_producto, Nombre, Fecha_registro, Pais, Genero, Edad, Nivel_ingresos, Ciudad]
Index: []

In [97]:
# Tratamiento de valores Desconocido en el Nivel de ingresos.
# Reviso los valores de Nivel de ingresos desconocidos por Edad

df_nivelingresos_desconocido = df_unido[
    df_unido['Nivel_ingresos'] == 'Desconocido'
][['Nivel_ingresos', 'Edad']]

df_nivelingresos_desconocido.head(10)

           Nivel_ingresos  Edad
Id_cliente
1             Desconocido    50
1             Desconocido    50
1             Desconocido    50
1             Desconocido    50
1             Desconocido    50
1             Desconocido    50
1             Desconocido    50
1             Desconocido    50
1             Desconocido    50
1             Desconocido    50

In [98]:
# Normalizo los niveles de Ingresos según rangos de edades
# De 18 a 30 = Bajo, de 30 a 40 = Medio, de 40 a 60 = Alto, de 60 a 90 = Medio

df_unido.loc[(df_unido['Nivel_ingresos'] == 'Desconocido') & (df_unido['Edad'] >= 18) & (df_unido['Edad'] < 30), 'Nivel_ingresos'] = 'Bajo'
df_unido.loc[(df_unido['Nivel_ingresos'] == 'Desconocido') & (df_unido['Edad'] >= 30) & (df_unido['Edad'] < 40), 'Nivel_ingresos'] = 'Medio'
df_unido.loc[(df_unido['Nivel_ingresos'] == 'Desconocido') & (df_unido['Edad'] >= 40) & (df_unido['Edad'] < 60), 'Nivel_ingresos'] = 'Alto'
df_unido.loc[(df_unido['Nivel_ingresos'] == 'Desconocido') & (df_unido['Edad'] >= 60) & (df_unido['Edad'] < 90), 'Nivel_ingresos'] = 'Medio'

In [99]:
# Compruebo que no quedan valores Desconocido en la columna Nivel_ingresos
df_unido[df_unido['Nivel_ingresos'] == 'Desconocido']

Empty DataFrame
Columns: [Id_venta, Fecha_venta, Importe, Producto, Cantidad, Descuento, Canal, Region, Estado, Zona_envio, Metodo_envio, Peso_paquete, Rango_valor_pedido, Coste_envio, Id_canal, Id_producto, Nombre, Fecha_registro, Pais, Genero, Edad, Nivel_ingresos, Ciudad]
Index: []

In [100]:
# Tratamiento de valores desconocidos en la columna Region. Reviso los valores de Region desconocidos por Ciudad
df_unido[df_unido['Region'] == 'Desconocido'].shape[0]

2592

In [101]:
# Sustituyo los valores Desconocido de Region según la Region de la ciudad de la última venta del mismo id_cliente
df_region_cliente_ref = (
    df_unido[df_unido['Region'] != 'Desconocido']  
    .assign(_fecha_venta=pd.to_datetime(
        df_unido.loc[df_unido['Region'] != 'Desconocido', 'Fecha_venta'],
        dayfirst=True,
        errors='coerce'
    ))
    .sort_values('_fecha_venta')                    
    .groupby(level='Id_cliente')                    
    .tail(1)                                        
    .reset_index()[['Id_cliente', 'Region']]        
)

In [102]:
# Uno esta tabla con el DataFrame original
df_unido = df_unido.merge(df_region_cliente_ref, on='Id_cliente', how='left', suffixes=('', '_ref'))

In [103]:
# Sustituir solo los valores Desconocido
df_unido.loc[df_unido['Region'] == 'Desconocido', 'Region'] = \
    df_unido.loc[df_unido['Region'] == 'Desconocido', 'Region_ref']

In [104]:
# Elimino la columna auxiliar
df_unido.drop(columns=['Region_ref'], inplace=True)

In [105]:
# Compruebo cuantos Desconocidos quedan
df_unido[df_unido['Region'] == 'Desconocido'].shape[0]

0

In [106]:
# Compruebo en mi DataFrame
df_unido[df_unido['Region'] == 'Desconocido'].head()

Empty DataFrame
Columns: [Id_cliente, Id_venta, Fecha_venta, Importe, Producto, Cantidad, Descuento, Canal, Region, Estado, Zona_envio, Metodo_envio, Peso_paquete, Rango_valor_pedido, Coste_envio, Id_canal, Id_producto, Nombre, Fecha_registro, Pais, Genero, Edad, Nivel_ingresos, Ciudad]
Index: []

In [107]:
# Tratamiento de valores desconocidos en la columna Zona envio. 
# Reviso los valores de Zona envio desconocidos por Ciudad

df_unido[df_unido['Zona_envio'] == 'Desconocido'].shape[0]

2592

In [108]:
# Sustituyo los valores Desconocido de Zona envio según la Zona envio de la ciudad de la última venta del mismo id_cliente
df_zona_cliente_ref = (
    df_unido.loc[
        df_unido['Zona_envio'].ne('Desconocido'),
        ['Id_cliente', 'Zona_envio', 'Fecha_venta']
    ]
    .assign(
        _fecha_venta=lambda df: pd.to_datetime(
            df['Fecha_venta'],
            dayfirst=True,
            errors='coerce'
        )
    )
    .sort_values('_fecha_venta')
    .drop_duplicates('Id_cliente', keep='last')
    [['Id_cliente', 'Zona_envio']]
)

In [109]:
# Uno esta tabla con el DataFrame original
df_unido = df_unido.merge(df_zona_cliente_ref, on='Id_cliente', how='left', suffixes=('', '_ref'))

In [110]:
# Sustituir solo los valores Desconocido
df_unido.loc[df_unido['Zona_envio'] == 'Desconocido', 'Zona_envio'] = \
    df_unido.loc[df_unido['Zona_envio'] == 'Desconocido', 'Zona_envio_ref']

In [111]:
# Elimino la columna auxiliar
df_unido.drop(columns=['Zona_envio_ref'], inplace=True)

In [112]:
# Compruebo cuantos Desconocidos quedan
df_unido[df_unido['Zona_envio'] == 'Desconocido'].shape[0]

0

In [113]:
# Compruebo en mi DataFrame
df_unido[df_unido['Region'] == 'Desconocido'].head()

Empty DataFrame
Columns: [Id_cliente, Id_venta, Fecha_venta, Importe, Producto, Cantidad, Descuento, Canal, Region, Estado, Zona_envio, Metodo_envio, Peso_paquete, Rango_valor_pedido, Coste_envio, Id_canal, Id_producto, Nombre, Fecha_registro, Pais, Genero, Edad, Nivel_ingresos, Ciudad]
Index: []

In [114]:
# Compruebo que no hay mas columnas con valores Desconocidos
(df_unido == 'Desconococido').any()

Id_cliente            False
Id_venta              False
Fecha_venta           False
Importe               False
Producto              False
Cantidad              False
Descuento             False
Canal                 False
Region                False
Estado                False
Zona_envio            False
Metodo_envio          False
Peso_paquete          False
Rango_valor_pedido    False
Coste_envio           False
Id_canal              False
Id_producto           False
Nombre                False
Fecha_registro        False
Pais                  False
Genero                False
Edad                  False
Nivel_ingresos        False
Ciudad                False
dtype: boolean

In [115]:
# Compruebo que no quedan columnas con valores NA
df_unido.isna().sum()

Id_cliente            0
Id_venta              0
Fecha_venta           0
Importe               0
Producto              0
Cantidad              0
Descuento             0
Canal                 0
Region                0
Estado                0
Zona_envio            0
Metodo_envio          0
Peso_paquete          0
Rango_valor_pedido    0
Coste_envio           0
Id_canal              0
Id_producto           0
Nombre                0
Fecha_registro        0
Pais                  0
Genero                0
Edad                  0
Nivel_ingresos        0
Ciudad                0
dtype: int64

In [116]:
df_unido['Region'].unique()

<StringArray>
['North', 'West', 'South', 'East', 'south', 'west', 'east', 'north']
Length: 8, dtype: str

In [117]:
# Reemplazar valores en español
df_unido['Region'] = df_unido['Region'].replace(
    {
        r'(?i)^west$': 'Oeste',
        r'(?i)^south$': 'Sur',
        r'(?i)^north$': 'Norte',
        r'(?i)^east$': 'Este'
    },
    regex=True
)

In [118]:
df_unido['Estado'].unique()

<StringArray>
['Cancelled', 'Shipped', 'Pending', 'Completed']
Length: 4, dtype: str

In [119]:
# Reemplazar valores en español
df_unido['Estado'] = (
    df_unido['Estado']
    .astype(str)
    .str.strip()
    .replace({'Shipped': 'Enviado',
              'Completed': 'Completado',
              'Pending': 'Pendiente',
              'Cancelled': 'Cancelado'
              })
)

In [120]:
df_unido['Estado'].unique()

<StringArray>
['Cancelado', 'Enviado', 'Pendiente', 'Completado']
Length: 4, dtype: str

In [121]:
# Normalizo los valores de Nombre. Eliminar espacios, poner letras capitales
df_unido['Nombre'] = (
    df_unido['Nombre']
    .astype(str)
    .str.strip()                
    .str.replace(r'\s+', ' ', regex=True)   
    .str.title()                
)

In [122]:
# Voy a añadir otra columna Antiguedad para determinar la duración en años del cliente desde la fecha registro hasta hoy

# Calculo la antigüedad del cliente en años, sin decimales, usando la fecha de registro y la fecha actual
fecha_registro = pd.to_datetime(
    df_unido['Fecha_registro'],
    errors='coerce',
    dayfirst=True
)

df_unido['Antiguedad'] = (
    (pd.Timestamp.today().normalize() - fecha_registro).dt.days // 365.25
)

In [123]:
df_unido[['Fecha_registro', 'Antiguedad']].head()

  Fecha_registro  Antiguedad
0     16/02/2017         9.0
1     16/02/2017         9.0
2     16/02/2017         9.0
3     16/02/2017         9.0
4     16/02/2017         9.0

In [124]:
df_unido.head()

,Id_cliente,Id_venta,Fecha_venta,Importe,Producto,Cantidad,Descuento,Canal,Region,Estado,Zona_envio,Metodo_envio,Peso_paquete,Rango_valor_pedido,Coste_envio,Id_canal,Id_producto,Nombre,Fecha_registro,Pais,Genero,Edad,Nivel_ingresos,Ciudad,Antiguedad
0,1,S16971,31/05/2017,214.46,Dispositivo G,5,10.0,En Linea,Norte,Cancelado,Zone 1,Standard,7.5,Medio,15.75,Tienda1,PROD-007,Steve Brown,16/02/2017,EE.UU,Hombre,50,Alto,Phoenix,9.0
1,1,S16302,24/01/2016,132.98,Dispositivo H,5,0.0,M-Commerce,Norte,Enviado,Zone 1,Express,7.5,Medio,20.25,Tienda2,PROD-008,Steve Brown,16/02/2017,EE.UU,Hombre,50,Alto,Phoenix,9.0
2,1,S33097,05/04/2016,253.95,Dispositivo B,6,0.0,En Linea,Oeste,Cancelado,Zone 4,Standard,9.0,Medio,15.30,Tienda1,PROD-002,Steve Brown,16/02/2017,EE.UU,Hombre,50,Alto,Phoenix,9.0
3,1,S39629,14/01/2021,348.60,Dispositivo E,3,0.0,En Linea,Sur,Pendiente,Zone 2,Standard,4.5,Medio,10.35,Tienda1,PROD-005,Steve Brown,16/02/2017,EE.UU,Hombre,50,Alto,Phoenix,9.0
4,1,S37229,07/11/2015,652.46,Dispositivo B,5,0.0,En Tienda,Sur,Completado,Zone 2,Pick-up,7.5,Alto,5.75,Tienda4,PROD-002,Steve Brown,16/02/2017,EE.UU,Hombre,50,Alto,Phoenix,9.0

In [125]:
# Voy a cambiar la columna Id cliente por indice.

if 'Id_cliente' in df_unido.columns:
    df_unido = df_unido.set_index('Id_cliente')

df_unido.index.name = 'Id_cliente'
df_unido.head()

,Id_venta,Fecha_venta,Importe,Producto,Cantidad,Descuento,Canal,Region,Estado,Zona_envio,Metodo_envio,Peso_paquete,Rango_valor_pedido,Coste_envio,Id_canal,Id_producto,Nombre,Fecha_registro,Pais,Genero,Edad,Nivel_ingresos,Ciudad,Antiguedad
Id_cliente,,,,,,,,,,,,,,,,,,,,,,,,
1,S16971,31/05/2017,214.46,Dispositivo G,5,10.0,En Linea,Norte,Cancelado,Zone 1,Standard,7.5,Medio,15.75,Tienda1,PROD-007,Steve Brown,16/02/2017,EE.UU,Hombre,50,Alto,Phoenix,9.0
1,S16302,24/01/2016,132.98,Dispositivo H,5,0.0,M-Commerce,Norte,Enviado,Zone 1,Express,7.5,Medio,20.25,Tienda2,PROD-008,Steve Brown,16/02/2017,EE.UU,Hombre,50,Alto,Phoenix,9.0
1,S33097,05/04/2016,253.95,Dispositivo B,6,0.0,En Linea,Oeste,Cancelado,Zone 4,Standard,9.0,Medio,15.30,Tienda1,PROD-002,Steve Brown,16/02/2017,EE.UU,Hombre,50,Alto,Phoenix,9.0
1,S39629,14/01/2021,348.60,Dispositivo E,3,0.0,En Linea,Sur,Pendiente,Zone 2,Standard,4.5,Medio,10.35,Tienda1,PROD-005,Steve Brown,16/02/2017,EE.UU,Hombre,50,Alto,Phoenix,9.0
1,S37229,07/11/2015,652.46,Dispositivo B,5,0.0,En Tienda,Sur,Completado,Zone 2,Pick-up,7.5,Alto,5.75,Tienda4,PROD-002,Steve Brown,16/02/2017,EE.UU,Hombre,50,Alto,Phoenix,9.0

In [126]:
# Convierto el archivo de Notebook a archivo csv para utilizarlo en próximos analisis.

df_unido.to_csv("df_unido.csv", index=True)